# Information for compile
# exclude: ["node_modules", "gulpfile.js", "package.json", "Gemfile", "README.md", "resources", "run"]
exclude: ["node_modules", "gulpfile.js", "package.json", "Gemfile", "README.md", "run"]

include: ["install.sh", "msa.pdf"]

baseurl:

plugins:
  - jekyll-redirect-from

# the base hostname & protocol for your site
url: https://diode.io

####################################
######   Optional Features    ######
####################################
smooth-scroll: false

####################################
#############   Tags    ############
####################################

tagurl: 'blog/tags.html#'

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: Diode&#8480; - Reclaim Your Digital Sovereignty
# Meta description
description: Diode enables digital sovereignty in everyday interactions.
# Website language
lang: en-US
# Header Title
header-title: <strong>Let's upgrade the Web</strong>
# Header Tagline
header-tagline: Web2 security is broken
twitter_username: 'diode_chain'

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: Watch the Video
  url: https://player.vimeo.com/video/318384993?autoplay=1

# Secondary Buttons
header-secondary-button:
  title: BlockQuick Paper
  url: https://eprint.iacr.org/2019/579.pdf


####################################
######  Global Navigation     ######
####################################

navigation:
- title: Solutions
  link: solutions/
  ft_order: 1
  subs:
    - title: Private Collaboration
      ft_title: Private Collaboration
      link: solutions/private-collaboration
    - title: File Sharing
      ft_title: File Sharing
      link: solutions/file-sharing
    - title: Backup
      ft_title: Backup
      link: solutions/backup
    - title: Remote Work
      ft_title: Remote Work
      link: solutions/remote-work
    - title: Asset Management
      ft_title: Asset Management
      link: solutions/asset-management
    - title: Serverless Communications
      ft_title: Serverless Communications
      link: solutions/serverless-communications
- title: Products
  link: products/
  ft_order: 2
  subs:
    - title: dDrive
      ft_title: dDrive
      link: products/d-drive
    - title: Diode CLI
      ft_title: CLI
      link: products/diode-cli
    - title: Diode Network
      ft_title: Network
      link: products/diode-network
- title: Pricing
  link: pricing/
  ft_order: 4
- title: Blog
  link: blog/
  ft_order: 5
- title: Resources
  link: resources/
  ft_order: 3
  subs:
    - title: How It Works
      ft_title: How It Works
      link: resources/how-it-works
    - title: About
      ft_title: About
      link: resources/about
    - title: Docs
      ft_title: Docs
      link: https://support.diode.io/
      target: _blank
    - title: Download
      ft_title: Download
      link: resources/download
    - title: Explorer
      ft_title: Explorer
      link: prenet
- title: <i class="fab fa-telegram-plane"></i>
  link: https://t.me/diode_chain
  target: _blank
- title: Download
  link: resources/download/
  is_button: true
  target: _blank


#################################
######  Breadcrumbs label  ######
#################################
breadcrumbs:
  solutions: Solutions
  remote-work: Remote Work
  private-storage: Private Storage
  streaming-video: Streaming Video
  healthcare-and-compliance: Healthcare & Compliance
  internet-of-things: Internet of Things
  it-and-developers: IT and Developers
  serverless-communications: Serverless Communications

  products: Products
  d-drive: dDrive
  diode-cli: Diode CLI
  diode-network: Diode Network
  pricing: Pricing

  blog: Blog

  resources: Resources
  how-it-works: How it Works
  about: About
  download: Download
  explorer: Explorer
  docs: Docs


####################################
######  Quick links of footer ######
####################################
quick_links:
- title: Solutions
  link: solutions/
- title: Products
  link: products/
- title: Pricing
  link: pricing/
- title: Blog
  link: blog/
- title: Resources
  link: resources/
- title: Privacy Policy
  link: privacy-policy/

#############################
######  Global Links   ######
#############################
links:
  # Common Links
  learn_more: 'resources/how-it-works/'
  contact_us: 'https://t.me/diode_chain'
  get_a_demo: 'products/pricing/'
  try_it_out: 'products/pricing/'
  download: 'resources/download/'

  # Social Links
  youtube: 'https://www.youtube.com/channel/UC3b5voADiipUmq1Q-vtPKsA'
  # pinterest: '#'
  # facebook: '#'
  twitter: 'https://twitter.com/diode_chain'
  telegram: 'https://t.me/diode_chain'
  github: 'https://github.com/diodechain'
  # google-plus: '#'
  vimeo: 'https://vimeo.com/diodechain'

#########################
######  Downloads  ######
#########################
d-drive:
  title: Diode Drive
  title-1: Diode Drive
  description: A cloud experience for your local storage - install on your computer, server, or device and start collaborating!
  # for solutions page(desktop)
  description-1: dDrive combines the privacy and compliance benefits of local storage with the benefits and efficiency of remote access.
  # for solutions page(mobile)
  description-2: Existing file servers and new Diode-enabled NAS systems can use Diode Drive to combine the privacy and compliance benefits of local storage with the benefits and efficiency of remote access.
  icon: images/diode-drive.png
  learn-more: 'products/d-drive/'
  download-base: https://github.com/diodechain/diode_drive_feedback/releases/download/v1.0.0/
  downloads:
  # - title: <i class="fab fa-raspberry-pi"></i> Raspberry Pi (ARM)
  #   link: diode_linux_arm.zip
  #   name: Raspberry Pi
  #   id: raspberry-pi
  - title: <i class="fab fa-apple"></i> MacOS X
    link: dDrive-1.0.0.dmg
    name: MacOS
    id: macos
  - title: <i class="fab fa-windows"></i> Windows (64-bit)
    link: dDrive-1.0.0-win32.signed.exe
    name: Windows
    id: windows
  - title: <i class="fab fa-linux"></i> Linux (64-bit)
    link: dDrive-1.0.0-linux-x86_64.run
    name: Linux
    id: linux
diode-cli:
  title: Diode CLI
  description: Serverless remote access for your IT assets, localhost websites / webservices, and data/video streams.
  # for solution page(desktop)
  description-1: The Diode CLI is used to maintain systems in hard-to-access facilities and to securely publish data streams and web properties.
  icon: images/diode-client.png
  learn-more: 'products/diode-cli/'
  download-command: 'curl -Ssf https://diode.io/install.sh | sh'
  download-base: https://github.com/diodechain/diode_go_client/releases/download/v0.10.2/
  downloads:
  - title: <i class="fab fa-raspberry-pi"></i> Raspberry Pi (ARM)
    link: diode_linux_arm.zip
    name: Raspberry Pi
    id: raspberry-pi
  - title: <i class="fab fa-raspberry-pi"></i> Raspberry Pi 64bit (ARM64)
    link: diode_linux_arm64.zip
    name: Raspberry Pi 64bit
  - title: <i class="fab fa-apple"></i> MacOS X
    link: diode_darwin_amd64.zip
    name: MacOS
    id: macos
  - title: <i class="fas fa-cube"></i> MacOS Package
    link: diode_darwin.pkg
    name: MacOS Package
    id: macos-package
  - title: <i class="fab fa-windows"></i> Windows (64-bit)
    link: diode_windows_amd64.zip
    name: Windows
    id: windows
  - title: <i class="fab fa-linux"></i> Linux (64-bit)
    link: diode_linux_amd64.zip
    name: Linux
    id: linux
# for only solution pages (mobile)
diode-network:
  title: Diode Network
  learn-more: 'products/diode-network/'
  description: The Diode Network is the world’s only fully decentralized communications network capable of supporting the needs of private, secure communications for the enterprise.
  link: 'https://support.diode.io/category/cck0x29491'


#########################
######   Widgets   ######
#########################

# Google Map JS api
# This is my api for this template
key-api: AIzaSyDbnxVZQannH0GF4gtnnBFPiP9ofm2WqGs
map-text: Sera Google Map
map-text-location: Bucharest, Romania
map-lat: 44.4267674
map-lng: 26.102538399999958

# Enter your Mailchimp User ID and Campaign ID
#####################################
############   About us   ###########
#####################################
about-us-title: Diode<sup>sm</sup>
about-us-description: >-
  Diode is responsible for governance and issuance of Diode Tokens, governance and maintenance of the Diode Network, and growing the ecosystem surrounding both.  The Diode Network is formed by the producers and miners who run instances of the Diode Chain&trade; Software.  The Diode Chain Software’s development and configuration management is provided by Diode.  Users of the Diode Network must use Diode Tokens to be granted access to the Diode Network’s unique capabilities for secure IoT communications.  Diode manages the issuance (block rewards) and other tokenomics for Diode Tokens.
  
#####################################
####### Diode Chain Features  #######
#####################################
chain-features-title: What is the Diode Chain<sup>tm</sup> software?
chain-features-description:

  #
# Diode Chain Features
#
chain-features:

# Feature
- title: Edge Connector
  description: >-
    Designed for microchips Diode Chains edge connector software runs even on very constrained client 
    devices. Written in protable C and implemening Diodes BlockQuick&trade; algorithm this piece of
    sofware allos to connect real world microchips such as the TI CC3220, development boards such as
    Arduino Yun and Industrial Gateways securely to the IoT cloud. With 10x less memory than 
    competitive products it's delivering 1000x times higher security for endpoint devices.

  icon: svgs/security.svg

# Feature
- title: Efficient & Secure Mining
  description: >-
    The Diode Chain software bundles the StakeWork&trade; consensus algorithm, providing more than 3x
    better energy efficiency compared with BitCoin and Ethereum while providing effective protections
    against Proof-Of-Work attacks. The algorithm is bundled with both the edge connector and the
    mining node software providing providing reference implementations.  

  icon: svgs/streaming.svg

# Feature
- title: Mining Node Sofware
  description: >-
    The full nodes of the Diode network are Ethereum VM and Ethereum RPC compatible offering 
    developers access to the full set of the development tools of the Ethereum Ecosystem
    such as remix and solidity. The Diode Chain software bundle contains the full reference
    implementation allowing easy operation in datacanters and mining operations. 

  icon: svgs/lower_cost.svg


#####################################
############# Our Blog ##############
#####################################
blog-name: Diode Team Blog
blog-title: Newest Articles
blog-description: >-
  As we're working on rolling out the next evolutionary steps of the Diode Network we will be 
  posting updates regularly. Also keep track of our twitter account to get all the latest news.


#####################################
############### Team ################
#####################################
team-title: Team
team-description: >-
  Our team consists of true IoT experts from both the business and the technology side. We're dedicated
  to a secure IoT future!

#####################################
#############   Footer   ############
#####################################
footer-description: >-
  <a href="https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/"     title="Flaticon">www.flaticon.com</a><br/>
  Icons made by <a href="https://www.flaticon.com/authors/smashicons" title="Smashicons">Smashicons</a> from <a href="https://www.flaticon.com/"     title="Flaticon">www.flaticon.com</a>
footer-copyright-text: DIODE
footer-copyright-url: https://diode.io/
footer-copyright-year: 2021

#########################
######   Widgets   ######
#########################

collections:
  posts:
    output: true 
    permalink: :categories/:title-:short_year:y_day/
  team:
    output: true 
    permalink: team/:name.html
  jobs:
    output: true
    permalink: jobs/:name.html

defaults:
  - scope:
      path: "_team"
      type: team
    values:
      layout: postlist
      tagline: All Articles By
      type: team
  - scope:
      path: "_jobs"
      type: jobs
    values:
      layout: job
      type: jobs
    
