# Information for compile
exclude: ["node_modules", "gulpfile.js", "package.json", "Gemfile", "README.md", "resources", "run"]
include: ["install.sh", "msa.pdf"]

baseurl:

plugins:
  - jekyll-redirect-from

# the base hostname & protocol for your site
url: https://diode.io

####################################
######   Optional Features    ######
####################################
smooth-scroll: false

####################################
#############   Tags    ############
####################################

tagurl: 'blog/tags.html#'

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: Diode&#8480; - The IoT Blockchain Network that actually works on small devices
# Meta description
description: The First Super Light Client and Blockchain Network for IoT, ARM, ESP32, Arduino, RaspberryPI and other embedded MCU
# Website language
lang: en-US
# Header Title
header-title: <strong>Let's upgrade the Web</strong>
# Header Tagline
header-tagline: Web2 security is broken

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: Watch the Video
  url: https://player.vimeo.com/video/318384993?autoplay=1

# Secondary Buttons
header-secondary-button:
  title: BlockQuick Paper
  url: https://eprint.iacr.org/2019/579.pdf


####################################
######  Global Navigation     ######
####################################

navigation:
- title: Home
  link: #home
- title: Blog
  link: blog/
- title: Docs
  link: https://support.diode.io
- title: Download
  link: download/
- title: Explorer
  link: prenet/
- title: <i class="fi flaticon-telegram"></i>
  link: https://t.me/diode_chain
  target: _blank
- title: <i class="fi flaticon-twitter"></i>
  link: https://twitter.com/diode_chain
  target: _blank
- title: <i class="fi flaticon-github"></i>
  link: https://github.com/diodechain
  target: _blank


####################################
######  Global Social Links   ######
####################################
youtube: 'https://www.youtube.com/channel/UC3b5voADiipUmq1Q-vtPKsA'
# pinterest: '#'
# facebook: '#'
twitter: 'https://twitter.com/diode_chain'
twitter_username: 'diode_chain'
telegram: 'https://t.me/diode_chain'
# google-plus: '#'
# vimeo: '#'

#########################
######  Downloads  ######
#########################
download-base: https://github.com/diodechain/diode_go_client/releases/download/v0.4.6/
downloads:
- title: <i class="fab fa-raspberry-pi"></i> Raspberry Pi (ARM)
  link: diode_linux_arm.zip
  id: Raspberry Pi
- title: <i class="fab fa-apple"></i> MacOS X
  link: diode_darwin_amd64.zip
  id: MacOS
- title: <i class="fas fa-cube"></i> MacOS Package
  link: diode_darwin.pkg
  id: MacOS
- title: <i class="fab fa-windows"></i> Windows (64-bit)
  link: diode_windows_amd64.zip
  id: Windows
- title: <i class="fab fa-linux"></i> Linux (64-bit)
  link: diode_linux_amd64.zip
  id: Linux

#########################
######   Widgets   ######
#########################

# Google Map JS api
# This is my api for this template
key-api: AIzaSyDbnxVZQannH0GF4gtnnBFPiP9ofm2WqGs
map-text: Sera Google Map
map-text-location: Bucharest, Romania
map-lat: 44.4267674
map-lng: 26.102538399999958

# Enter your Mailchimp User ID and Campaign ID
#####################################
############   About us   ###########
#####################################
about-us-title: Diode<sup>sm</sup>
about-us-description: >-
  Diode is responsible for governance and issuance of Diode Tokens, governance and maintenance of the Diode Network, and growing the ecosystem surrounding both.  The Diode Network is formed by the producers and miners who run instances of the Diode Chain&trade; Software.  The Diode Chain Software’s development and configuration management is provided by Diode.  Users of the Diode Network must use Diode Tokens to be granted access to the Diode Network’s unique capabilities for secure IoT communications.  Diode manages the issuance (block rewards) and other tokenomics for Diode Tokens.
  
#####################################
####### Diode Chain Features  #######
#####################################
chain-features-title: What is the Diode Chain<sup>tm</sup> software?
chain-features-description:

  #
# Diode Chain Features
#
chain-features:

# Feature
- title: Edge Connector
  description: >-
    Designed for microchips Diode Chains edge connector software runs even on very constrained client 
    devices. Written in protable C and implemening Diodes BlockQuick&trade; algorithm this piece of
    sofware allos to connect real world microchips such as the TI CC3220, development boards such as
    Arduino Yun and Industrial Gateways securely to the IoT cloud. With 10x less memory than 
    competitive products it's delivering 1000x times higher security for endpoint devices.

  icon: svgs/security.svg

# Feature
- title: Efficient & Secure Mining
  description: >-
    The Diode Chain software bundles the StakeWork&trade; consensus algorithm, providing more than 3x
    better energy efficiency compared with BitCoin and Ethereum while providing effective protections
    against Proof-Of-Work attacks. The algorithm is bundled with both the edge connector and the
    mining node software providing providing reference implementations.  

  icon: svgs/streaming.svg

# Feature
- title: Mining Node Sofware
  description: >-
    The full nodes of the Diode network are Ethereum VM and Ethereum RPC compatible offering 
    developers access to the full set of the development tools of the Ethereum Ecosystem
    such as remix and solidity. The Diode Chain software bundle contains the full reference
    implementation allowing easy operation in datacanters and mining operations. 

  icon: svgs/lower_cost.svg


#####################################
############# Our Blog ##############
#####################################
blog-name: Diode Team Blog
blog-title: Newest Articles
blog-description: >-
  As we're working on rolling out the next evolutionary steps of the Diode Network we will be 
  posting updates regularly. Also keep track of our twitter account to get all the latest news.


#####################################
############### Team ################
#####################################
team-title: Team
team-description: >-
  Our team consists of true IoT experts from both the business and the technology side. We're dedicated
  to a secure IoT future!

#####################################
#############   Footer   ############
#####################################
footer-description: >-
  <a href="https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/"     title="Flaticon">www.flaticon.com</a><br/>
  Icons made by <a href="https://www.flaticon.com/authors/smashicons" title="Smashicons">Smashicons</a> from <a href="https://www.flaticon.com/"     title="Flaticon">www.flaticon.com</a>
footer-copyright-text: DIODE
footer-copyright-url: https://diode.io/
footer-copyright-year: 2020

#########################
######   Widgets   ######
#########################

collections:
  posts:
    output: true 
    permalink: :categories/:title-:short_year:y_day/
  team:
    output: true 
    permalink: team/:name.html

defaults:
  - scope:
      path: "_team"
      type: team
    values:
      layout: postlist
      tagline: All Articles By
      type: team
    