# General Settings
name: Diode
title: Diode&#8482;
description: Diode enables digital sovereignty in everyday interactions.
url: https://diode.io


# Theme Settings
theme: minima
minima:
  date_format: "%b %-d, %Y"
sass:
  style: compressed
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-sitemap


# Path
path:
  images: "/assets/img/"
  styles: "/assets/css/"
  scripts: "/assets/js/"
  favicon: "/assets/favicon/"


# Navigation
nav:
- title: Products
  url: "/products/"
  sub:
  - title: Diode Collab
    url: "/products/collab/"
  - title: CLI
    url: "/products/cli/"
  - title: Vault
    url: "/products/vault/"
  - title: Network
    url: "/products/network/"
#- title: Use Cases
#  url: "/usecases/"
- title: Docs
  url: "https://docs.diode.io/"
  target: _blank
#- title: Pricing
#  url: "/pricing/" 
- title: About Us
  url: "/about/"
  sub:
#  - title: Download
#    url: "/download/"
  - title: How it works
    url: "/how-it-works/"
#  - title: Explore the network
#    url: "https://diodenetwork.io"
#    target: _blank
  - title: Blog
    url: "/blog/"

# Other Links
links:
  download:
    title: Login
    url: "/download/"
  node:
    title: Run a Node
    url: "https://network.docs.diode.io/docs/"
  terms:
    title: Terms
    url: "/terms/"
  privacy:
    title: Privacy Policy
    url: "/privacy-policy/"
  thanks:
    title: Thank You
    url: "/download/thanks/"


# Social Networks
social:
  discord: "https://discord.gg/qdGCAKJdHs"
  youtube: "https://www.youtube.com/channel/UC3b5voADiipUmq1Q-vtPKsA"
  # telegram: "https://t.me/diode_chain"
  twitter: "https://twitter.com/diode_chain"
  github: "https://github.com/diodechain"
  # matrix: "https://matrix.to/#/#diodechain:matrix.org"


# Download Links
download:
  app:
    macos: "https://download.diode.io/downloads/collab/dDrive-1.18.13.dmg"
    macos-checksum:
    windows: "https://download.diode.io/downloads/collab/dDrive-1.18.13.exe"
    windows-checksum:
    linux: "https://github.com/diodechain/diode_feedback/releases/download/v1.0.0/dDrive-1.18.13-linux-x86_64.run"
    linux-checksum: f774d7da1a937fc4e2e630c5b9bbf950bc0c1b4e
    raspberry-pi: "https://github.com/diodechain/diode_feedback/releases/download/v1.0.0/dDrive-1.18.13-linux-arm32.run"
    raspberry-pi-checksum: eab99f6654ad8b0d8d13e11a6c245090bea1308f
    raspberry-pi-64: "https://github.com/diodechain/diode_feedback/releases/download/v1.0.0/dDrive-1.18.13-linux-arm64.run"
    raspberry-pi-64-checksum: 168f6e49583200d3a1203541647aeb0863929b21
    ios: "https://apps.apple.com/us/app/diode-drive/id1605222443"
    ios-checksum:
    android: "https://play.google.com/store/apps/details?id=io.diode.drive"
    android-checksum: 
  cli:
    macos: "https://github.com/diodechain/diode_go_client/releases/download/v0.13.7/diode_darwin_amd64.zip"
    macos-checksum:
    macos-package: "https://github.com/diodechain/diode_go_client/releases/download/v0.13.7/diode_darwin.pkg"
    macos-package-checksum:
    windows: "https://github.com/diodechain/diode_go_client/releases/download/v0.13.7/diode_windows_amd64.zip"
    windows-checksum:
    linux: "https://github.com/diodechain/diode_go_client/releases/download/v0.13.7/diode_linux_amd64.zip"
    linux-checksum: 
    raspberry-pi: "https://github.com/diodechain/diode_go_client/releases/download/v0.13.7/diode_linux_arm.zip"
    raspberry-pi-checksum: 
    raspberry-pi-64: "https://github.com/diodechain/diode_go_client/releases/download/v0.13.7/diode_linux_arm64.zip"
    raspberry-pi-64-checksum: 


# Footer
copyright: "DIODE &copy; 2026, All Rights Reserved"
security:
  title: "Secure your perimeter."
  content: "Weâ€™re governed by the belief that technology should help people thrive. It should enhance our ability to operate, create, explore, educate, and innovate - unhindered."


# Collections
collections:
  usecases:
    output: true
    permalink: /:name/

# Blog Settings
paginate: 10
paginate_path: "/blog/:num"
tags_path: "/blog/tags"
permalink: "/blog/:title"


# Sitemap excludes
defaults:
- scope:
    path: "multisig/**/*.*"
  values:
    sitemap: false
- scope:
    path: "status/**/*.*"
  values:
    sitemap: false
- scope:
    path: "assets/**/*.*"
  values:
    sitemap: false
- scope:
    path: "vesting/**/*.*"
  values:
    sitemap: false
- scope:
    path: "staging/**/*.*"
  values:
    sitemap: false
- scope:
    path: "*.*"
  values:
    image: images/diode_og.png
