name: "CI"
on: ["push", "pull_request"]

jobs:
  install_test:
    name: "Install and run app"
    strategy:
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macOS-latest"]
        go: ["1.14.x"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - run: |
        cat install.sh | sh -s v0.3.3
        echo ~/opt/diode >> $GITHUB_PATH
      shell: bash
    # On windows the self-update does not fail but kills the client
    - if: runner.os != 'Windows' 
      run: diode config -list
      shell: bash
